# Generated by Django 4.1.7 on 2023-03-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_genres_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
                ('year', models.IntegerField(default=2023)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='website.card'),
        ),
    ]
