# Generated by Django 4.1.7 on 2023-03-25 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_card_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='website.genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
