# Generated by Django 4.1.7 on 2023-03-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
